disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "SzCORE - Epilepsy benchmarks"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/favicon.png"
description = "SzCORE is a framework for the validation of EEG based automated seizure detection algorithms."

[params.author]
name = "Jonathan Dan"
